dist: jammy
language: node_js
node_js:
  - 20
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
env:
  - NODE_ENV=production
  - PATH=$PATH:~/node_modules/.bin/
before_install:
  - npm i -g pnpm
install:
  - pnpm install
script:
  - cd ~/
  - pnpm test