dist: jammy
language: node_js
node_js:
  - 20
cache:
  npm: true
  directories:
    - "~/.pnpm-store"
env:
  - NODE_ENV=production
before_install:
  - npm i -g pnpm
install:
  - pnpm install
script:
  - ./node_modules/.bin/pnpm test