dist: jammy
language: node_js
node_js:
  - 20
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
env:
  - NODE_ENV=production
before_install:
  - npm i -g pnpm
install:
  - pnpm install
  - pnpm bin
script:
  - ~/.pnbpm-store/.bin/pnpm test