dist: jammy
language: node_js
node_js:
  - 20
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
env:
  - NODE_ENV=production
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm test