services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - nodemods:/app/node_modules
      - ./src:/app/src
      - ./test:/app/test
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
    entrypoint: ["pnpm", "dev"]
volumes:
  nodemods: